### ISSUE TITLE
Live tab values not refreshing

### ISSUE THREAD

**Issue by Hansorb** [dutu/poloLender#112]
Hi,

I do not know if it is supposed to refresh, but my live values are not live. I need to manual use refresh (f5) on chrome to get new values even tough the updated states keeps flashing "a few seconds ago".
There are no adBlockers active or anything. 

Anything i'm missing here?

**Comment by dutu** [comment]
The tables in "live" tab are updating  without the need to refresh the page manually. How do you determine the values are not refreshing? Can you give an example?

**Comment by Hansorb** [comment]
I compare the values to those of poloniex itself by looking at the lending page. Just to be complete: I meant the fee values of existing loans. Loans not created by the bot. They existed pre bot. But are shown ok when refreshing manually

**Comment by dutu** [comment]
There could be a slight sync time gap between the poloLender app and Poloniex site since they don't refresh at exactly same time. The time gap is probably i and the range of milliseconds or very few seconds in the worst case. 
Since Poloniex doesn't not provide a faster API method (neither for external apps like poloLender nor for own Web interface), it's best it can be done. 

Please also note that poloLender data is refreshed at higher speed than the Poloniex Web interface itself 
😊

**Comment by Hansorb** [comment]
I understand what you mean, but I actually mean "not updating. Not live". It does not matter how long I wait.

**Comment by Hansorb** [comment]
Can you give me a javascript method / variable to start looking at? I'm ok with trying to debug some by console. But since the application is quite new to me I need a pointer to the entrance :)

**Comment by Hansorb** [comment]
I seem to have more issues on chrome, like not continuing after login unless I refresh manually. Might be a local issue for me.... but I hardly experience other issues with websites...

**Comment by dutu** [comment]
fixed in the new version 1.3.1 that has just been released.
Let me know if it works as wanted

**Comment by Hansorb** [comment]
Both issues fixed. Thanks!
Will donate when my bot runs full time with a bit more coins
