### ISSUE TITLE
poloLender / poloLending-Advisor  disconnect

### ISSUE THREAD

**Issue by rTreutlein** [dutu/poloLender#12]
Hey,

so I have been thinking a bit and I think have these 2 things be separate can/is causing sub-optimal rates.
This is because if they where one system when calculating the rate it could consider if a loan is from you or not.
This can lead to the bot trying to undercut itself and I have seen that happen.

So it would be appreciated if you could open source the Advisor so that I may fix this. But since it's not already open I guess you are not planning on changing that. well asking doesn't cost anything.

**Comment by laxdog** [comment]
I would also like to see this.

**Comment by dutu** [comment]
The poloLending Advisor is aware of its own rates issued to the clients, hence a race condition with its own loans is not created.

It is however possible to have a race condition with another type of bot, but the poloLending advisor will still calculate the optimal rate for given circumstances and won't advise of sub-optimal rates. 

Right now it won't be possible for me to publish the source code since the advisor worker is part of a bigger system with several other workers doing different tasks. I will come spider separating the advisor code completely to have it published as an open source later.

**Comment by hithams** [comment]
Just checking on the status of the advisor code.  I am looking forward to it just for ensured uptime.
