### ISSUE TITLE
Lend for 2+ days

### ISSUE THREAD

**Issue by avoloshko** [dutu/poloLender#22]
It would be nice to lend for longer periods of time if there is a spike. Maybe, it's reasonable to specify the maximum amount of BTC can be landed for 2+ days in the config file.

**Comment by dutu** [comment]
@avoloshko, although, some of the loans could be held for over 2 days, I have noted that the average holding times is never over 24 hours (usually 1-15 hours).
Hence in theory It would make sense to try lending for 2+ days, however the real benefit is not big, since most likely the loan will be release in less than 1 day. 

Secondly it would only make sense to lend for longer times when the rate is at peak. Now the question is how a peak can be determined. 
We are entering an area similar to trading technical analysis. 
Not sure if it is worth the effort since the loan holding time is pretty small in average.
Any suggestion?

**Comment by abletaz** [comment]
I find some borrowers don't bother canceling the loan even after the rate drops, and hold for a few days, so some logic/option to loan when above a certain rate for longer would be profitable.

However, also, I'd advise some caution about making 60 day loans generally - if a hardfork ever actually happens on bitcoin, Poloniex's policy is that the loaner doesn't receive both branches back, rather only whichever one poloniex considers is 'bitcoin', which could likely mean the loaner ends-up only getting back the coins on the minority chain ..... so while it doesn't look like happening soon, it is possible that at some point a hardfork could be announced less than 60 days in advance maybe .... personally 30 days is what I prefer as a safer limit.

**Comment by dutu** [comment]
Although it happens that loans on Poloniex are held over 2 days, the the average loan holding time is seldom over 12 hours (mostly 1-8 hours). 
Also trying to determine the peak may not give accurate results.
For these reasons I decided not to implement the feature to lend for more than 2 days.
