### ISSUE TITLE
wrong tax calculated!!! NO LENDING!

### ISSUE THREAD

**Issue by cj4c0b1** [dutu/poloLender#23]
about 2 days ago the bot start to try to loan with a wrong calculated tax and the result is that no loan offer wold be taken.

Anyone with the same issue ?

**Comment by cj4c0b1** [comment]
Its seems that was a miscalculation. the if the value suggested was divided by ten, it fits to the market.

**Comment by dutu** [comment]
Can you indicate the currency, time and lending rate when the perceived error occurred? 
Does it still happen after several hours? Reason for asking is because it is normal for the bot not to place lending offers at the rate on the top of the lending book, but rather place lending offers at higher rate and wait to be taken.

**Comment by dutu** [comment]
@cj4c0b1 I will close this since "no lending" is most likely due to bot waiting for a higher, more profitable rate (based on the average loan holding time). If you have additional question or concerns please don't hesitate to post them here.
