### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#46]
One tip, if you can add in the Bot it will be very useful, sometimes the bot places an order with a% above those that are available, but some of these are many bitcoins, for example 800,1000 bitcoins, if you can, The bot will calculate how many bitcoins are above our order so as not to take too long to lend

**Comment by dutu** [comment]
@tsebis, you don't have to worry about the volume of coins above your offer. The lending algorithm calculates the optimal rate and if the lending is not reaching your loan offer within the optimum time, the rate is lowered a bit and this is calculated continously. 

The algorithm calculates the optimum time without taking into consideration  the number of coins as an absolute number; this would not be a reliable parameter to calculate the best loan rate, since the lending volumes vary significantly over time due variation of trading volumes. During high lending volumes 10BTC above your lending offer is insignifiant, but during low lending volume it could be a big wall on the lending g book.
