### ISSUE TITLE
Issue: API indicator shows a problem every few seconds

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#51]
VPS which is running this app located within 1ms latency from poloniex servers, so it shouldn't be an issue. I made a short video of what's transpiring https://media.giphy.com/media/xUPGcjqOkcTOBFYor6/giphy.gif

**Comment by dutu** [comment]
@stranger29 , the API indicator turns into the "ban" icon when there is no API activity for 5 seconds.
Lately Poloniex server is slow in processing API calls and often the results are given in more than 5 seconds.

For these cases you see the API indicator as the "ban" icon. 
I agree with you this could be a bit misleading - I will update timer so that indicator shows the ban icon only after a longer interval.

**Comment by dutu** [comment]
@stranger29 thank you for reporting this issue.
it is now fixed in v0.8.3.
