### ISSUE TITLE
Feature request: compound interest

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#54]
@dutu, Could you please add compound Interest info to the report? 
smth like: "at 0.193899% (70.77%) (CI 101.24%)" 
we know that worst case it will be compounded every 2nd day and it's pretty simple math,
formula and explanation could be found here [http://www.thecalculatorsite.com/articles/finance/compound-interest-formula.php](url)
Thank you.

**Comment by dutu** [comment]
@stranger29, I will consider showing this in the GUI, but since the rates are widely varying over time the value would not be any good reflection of reality. In fact the same goes for the annual rate, but I've choosen to show it just to give an idea of what 0.193899% per day translates into per year (since most of us are used to understand an annual rate).

**Comment by stranger29** [comment]
@dutu, I completely understand that and how confusing or over-optimistic it could be.
but that is still a valid number which would be true in an ideal world with a constant rate :)

Also, do you think there is a way to somehow distinguish percentage of profit acquired due to compounding in performance review page?
I mean, i.e. we had started with 1 btc and bot was running for the year,
after 365 days we are reviewing results:
Initial balance: 1 btc
Avg. daily rate 0.20% (70% pa) (CI - 102%)
Earned: 1.02btc (0.32btc due to bidaily compounding)
Total 2.02btc

**Comment by dutu** [comment]
@stranger29, it's possible to show profit acquired due to compounding, however rates and amounts of individual loans would need to be taken into consideration, hence these would need to be stored in a database.

Having a database connected would make installation of the bot more complicated and I believe many user would prefer simple setup.

**Comment by dutu** [comment]
added in version 0.10.0
