### ISSUE TITLE
Minimum Amount loan

### ISSUE THREAD

**Issue by amber46** [dutu/poloLender#63]
Is it possible to establish a minimum loan volume?

**Comment by dutu** [comment]
@amber46, would you please detail on your request/question, I don't really understand it.

**Comment by amber46** [comment]
Maybe I do not understand the meaning of this bet
info: Loan taken    #205577466 BTC     0.00000005 at 0.174249% (63.60%), created 2017-06-17 20:56, expires in 2 days
The bot gives the loan any amount from the balance
Maybe it makes sense to specify less than what amount do not give in a loan?

**Comment by dutu** [comment]
1) the line you're mentioning indicates that the amount of  BTC 0.00000005 was taken as a loan. Note that it doesn't mean that the same amount was offered - you could have offer 1 BTC, but Poloniex only took 0.00000005 BTC from your offer (and most likely other amounts from other offers at the same rate or lower rate)  

2) as for "to specify less than what amount do not give in a loan": the bot offers for lending the funds as soon as available. It makes sense to do so instead of keeping available funds aside and wait.

**Comment by amber46** [comment]
I agree.
You are absolutely right.
