### ISSUE TITLE
Open source poloLending-Advisor?

### ISSUE THREAD

**Issue by pioug** [dutu/poloLender#77]
I am wondering if you plan to open source `poloLending-Advisor` too! It seems to be the single point of failure of poloLender right now. I am also curious about how you implement the lend offer optimisation and how it communicates with the poloLender clients. I would eventually like to self-host the full stack. I can understand if you want to keep the source, it's your work after all 👍 

Anyway, I love poloLender. It is working so well! Thank you for hosting the advisor and maintaining the lender engine ❤️

**Comment by dutu** [comment]
* The poloLending-Advisor is currently integrated with other scripts. Right now I don't have the bandwidth to work on implement it as a stand alone tool. 

This project started a couple of years ago from a personal need and I didn't have the intention to offer the lending strategy for public use. 
During the time I've seen a number of very popular lending bots, which unfortunately are not only inefficient, but also lead to race conditions, which in turn lead to lower and lower rates. This is when I decided to offer the strategy to wide use.

* Calculating the average-loan- holding-time is one of the main tasks of poloLending-Advisor. For this I have to continuously place loan offers at the top of the lending book. This leads to having relatively large amount of funds locked into lending and at non-optimal rates. Due to this I believe many users would not be able to allocate funds for this operation and run a poloLending-Advisor app on their own.

I agree with you that the poloLending-Advisor is a single point of failure. Even if it has been working for couple of years with almost no downtime, I'd love to transform it into a high availability system. 
However, it'll imply additional development and running cost.

**Comment by pioug** [comment]
That makes sense! I like your approach to optimise the rate 👍 and so far I don't have any complain about the uptime 😀

I am closing the issue, thank a lot for you reply!
